version: '3'

services:
  webapp:
    build: ./containers/webapp
    image: ``webapp``/webapp
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    stdin_open: true
    volumes:
      - ``webapp``-sync:/repos/``webapp``:nocopy
    depends_on:
      - db
    ports:
      - "20000:3000"
    command: bundle exec unicorn_rails -E development -c config/unicorn.rb

  db:
    build: ./containers/db
    image: ``webapp``/db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "20050:3306"

volumes:
  ``webapp``-sync:
    external: true
  db_data: {}
